pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
stage('Setup Environment') {
    steps {
        script {
            // Completely override PATH to exclude system Maven
            def mvnHome = tool 'maven_3.9.6'
            env.PATH = "${mvnHome}/bin:${env.JAVA_HOME}/bin:${env.PATH}"
            
            // Verify which Maven is being used
            sh '''
                echo "Full PATH: ${PATH}"
                which mvn
                mvn --version
            '''
        }
    }
}
        
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
